# Generated by Django 6.0.3 on 2026-04-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='zone',
            field=models.CharField(max_length=50),
        ),
    ]
